// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD29EFiZMx-L-n4LvpgHrl-8fW7O-xNQN0',
    appId: '1:993095345294:web:86053b4e737195c8d695df',
    messagingSenderId: '993095345294',
    projectId: 'student-management-app-28dd0',
    authDomain: 'student-management-app-28dd0.firebaseapp.com',
    storageBucket: 'student-management-app-28dd0.appspot.com',
    measurementId: 'G-L37B3SV6HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoyZEUAigIyqctaajIiDlsSy2oWT2NztM',
    appId: '1:993095345294:android:0039066d372e8323d695df',
    messagingSenderId: '993095345294',
    projectId: 'student-management-app-28dd0',
    storageBucket: 'student-management-app-28dd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjmtveNNTYpby1wLqIgOTYJB6F0SRdWKA',
    appId: '1:993095345294:ios:db54da83ec305ffad695df',
    messagingSenderId: '993095345294',
    projectId: 'student-management-app-28dd0',
    storageBucket: 'student-management-app-28dd0.appspot.com',
    iosBundleId: 'com.example.kudoswareAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjmtveNNTYpby1wLqIgOTYJB6F0SRdWKA',
    appId: '1:993095345294:ios:db54da83ec305ffad695df',
    messagingSenderId: '993095345294',
    projectId: 'student-management-app-28dd0',
    storageBucket: 'student-management-app-28dd0.appspot.com',
    iosBundleId: 'com.example.kudoswareAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD29EFiZMx-L-n4LvpgHrl-8fW7O-xNQN0',
    appId: '1:993095345294:web:51acd1506d06ed67d695df',
    messagingSenderId: '993095345294',
    projectId: 'student-management-app-28dd0',
    authDomain: 'student-management-app-28dd0.firebaseapp.com',
    storageBucket: 'student-management-app-28dd0.appspot.com',
    measurementId: 'G-Q5RBM60YRB',
  );
}
